### ISSUE TITLE
Add sound null safety

### ISSUE THREAD

**Issue by mars3142** [Dimibe/kraken_api#2]
It would be nice to add null safety to your package.

**Comment by Dimibe** [comment]
Hi @mars3142, I have just published a pre-release with null-safety. See on [pub.dev](https://pub.dev/packages/kraken_api/versions/2.0.0-nullsafety.0)

I will do some tests with it before releasing it as a real release. But anyway it should be fine for you to just use the pre-release until the real release is published.

**Comment by Dimibe** [comment]
Stable Release 2.0.0 with null-safety published.
